# Generated by Django 5.2 on 2025-04-09 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="call_duration",
            field=models.PositiveIntegerField(
                default=0, help_text="Duration in seconds"
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="room_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
